### PR TITLE
Adds support for email style local account

### PR DESCRIPTION
**Pull request by mediaformat**
Here's an attempt at supporting email style local accounts

### CODE REVIEW

**Comment by mediaformat** [comment]
Related to https://github.com/webfinger/webfinger.net/issues/28

**Comment by mediaformat** [comment]
First time using Golang, there is a logic error in the first part.

**Comment by mediaformat** [comment]
That was an accidental delete, code should be good to go

**Comment by willnorris** [comment]
fixed in 96ea8c8fe094f28d980228c1b70a8a8d99ae7ce3

**Pull request closed without merging**
